### ISSUE TITLE
API redirecting to HTTPS

### ISSUE THREAD

**Issue by crlsndrsjmnz** [udacity/ud843-QuakeReport#74]
When I open the application I get the following error:

```
com.example.android.quakereport E/QueryUtils: Error response code: 301
```

That is caused by the API, which is returning Response Code 301 (Moved Permanently) on [QueryUtils:109](https://github.com/udacity/ud843-QuakeReport/blob/lesson-four/app/src/main/java/com/example/android/quakereport/QueryUtils.java#L109), method `makeHttpRequest`.

Full response is:

> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>301 Moved Permanently</title></head><body><h1>Moved Permanently</h1><p>The document has moved <a href="https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&amp;starttime=2016-01-01&amp;endtime=2016-05-02&amp;minfelt=50&amp;minmagnitude=5">here</a>.</p></body></html>

**Comment by Naveenkhasyap** [comment]
@crlsndrsjmnz Hi I also faced this issue, earlier I thought this might be because of request method is Http not https but this didn't solve the issue, later by including Log statements I came to know that issue is in EarthquakeLoader constructor where we are assigning null to mUrl , Instead it should be the passed String Url which is an input param to constructor i.e. mUrl = url will work , then it worked for me .

**Comment by elit1910** [comment]
Thank YOU @Naveenkhasyap ! Worked for me!

**Comment by yvasilyev92** [comment]
I got the same issue but then I simply changed the "http..." in EarthquakeActivity to "https..." and that fixed everything, because according to the USGS API documentation found [here ](https://earthquake.usgs.gov/fdsnws/event/1/) the BASE URL is no longer
http://earthquake.usgs.gov/fdsnws/event/1/[METHOD[?PARAMETERS]]
but
https://earthquake.usgs.gov/fdsnws/event/1/[METHOD[?PARAMETERS]]

**Comment by aydinaytac** [comment]
I have just change the protocol from HTTP to HTTPS and the "response code: 301" error has gone 👍

**Comment by asadnawaz126** [comment]
None of these fixes work. Somone please help me

https://github.com/asadnawaz126/ud843-QuakeReport/tree/starting-point/app/src/main/java/com/example/android/quakereport
