### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by hitswa** [udacity/ud843-QuakeReport#86]
1. on line 191 of EarthquakeActivity, updateUi(earthquakes);  has an error saying cannot resolve method which Is true

2. In the lesson, you didn't even touch fragments but in the layout, I found one.

3. In code also there are certain code which Is never discussed in EarthquakeActivity, I am talking about SharedPreferences

4. There are various elements of the lesson which were unplanned and thought in a very rough way. Not easy to gulp by a beginner. I lost in midway and even after watching tutorials again and again, Not able to catch or gain desired output in the application. and when inspected GitHub commits code found to be slightly different.

I know many people may criticize me for my comments but I am a beginner in Android and if you get the concept doesn't mean everyone did. I request to such people, Instead of commenting prefer not comment if you disagree because you are here not to resolve the issue but maybe to laugh at someone's inability to understand, so better don't comment.

**Comment by jmquint00** [comment]
how did you get around the updateUi issue?

UPDATE....

there seems to be a line of code right above "updateUi(earthquakes);". That line reads...."mAdapter.addAll(earthquakes);", but it is commented out. 

if you un-comment that line and comment out the updateUi line the application will load. It seems to be working fine. I can see earthquake info that is consistent with the site info.

**Comment by kwieta** [comment]
@hitswa Guess you were lost on Networking / Threads & Parallelism (4.5).
(Shared) Preferences are the subject of the next lesson Networking / Preferences (4.7). If you've downloaded lesson-four branch from the Quake Report project, then the code from next lesson was already in it. Same with EarthquakePreferenceFragment you mentioned. You should check earlier branches because lesson-four one is the final stage for this app and that's not what you were looking for.

Good luck with the course, I was lost in threads & loaders too :)

**Comment by home2mars** [comment]
https://github.com/udacity/ud843-QuakeReport/commit/9cc44da0b021b828e90d797ab247ddd6c636ce36

**Comment by Rosariobc** [comment]
For me, the Threads & loaders chapter has been a challenge. I feel very lost, but keeping the work... reading and seeing many additional guides and tutorials and asking for help... I am also a beginner!

**Comment by chaudharynidhi** [comment]
E/SchedPolicy: add_tid_to_cgroup failed; fd=-1
how to clear this error
